package mil.nga.msi.geopackage.export

import mil.nga.geopackage.db.GeoPackageDataType
import mil.nga.mgrs.MGRS
import mil.nga.msi.datasource.port.Port
import mil.nga.msi.ui.map.cluster.MapAnnotation
import mil.nga.msi.ui.port.detail.asNonZeroOrNull
import mil.nga.sf.Point

class PortDefinition() : DataSourceDefinition {
   override val tableName = "ports"
   override val icon = MapAnnotation.Type.PORT.icon
   override val columns: List<FeatureColumn> = listOf(
      FeatureColumn("number", "World Port Index Number", GeoPackageDataType.INT),
      FeatureColumn("name", "Main Port Name", GeoPackageDataType.TEXT),
      FeatureColumn("latitude", "Latitude", GeoPackageDataType.DOUBLE),
      FeatureColumn("longitude", "Longitude", GeoPackageDataType.DOUBLE),
      FeatureColumn("position", "Position", GeoPackageDataType.TEXT),
      FeatureColumn("regionName", "Region Name", GeoPackageDataType.TEXT),
      FeatureColumn("alternateName", "Alternate Port Name", GeoPackageDataType.TEXT),
      FeatureColumn("unloCode", "UN/LOCODE", GeoPackageDataType.TEXT),
      FeatureColumn("countryName", "Country", GeoPackageDataType.TEXT),
      FeatureColumn("dodWaterBody", "World Water Body", GeoPackageDataType.TEXT),
      FeatureColumn("publicationNumber", "Sailing Directions or Publication", GeoPackageDataType.TEXT),
      FeatureColumn("chartNumber", "Standard Nautical Chart", GeoPackageDataType.TEXT),
      FeatureColumn("s57Enc", "IHO S-57 Electronic Navigational Chart", GeoPackageDataType.TEXT),
      FeatureColumn("s101Enc", "IHO S-101 Electronic Navigational Chart", GeoPackageDataType.TEXT),
      FeatureColumn("dnc", "Digital Nautical Chart", GeoPackageDataType.TEXT),
      FeatureColumn("tide", "Tidal Range (m)", GeoPackageDataType.INT),
      FeatureColumn("entranceWidth", "Entrance Width (m)", GeoPackageDataType.INT),
      FeatureColumn("channelDepth", "Channel Depth (m)", GeoPackageDataType.INT),
      FeatureColumn("anchorageDepth", "Anchorage Depth (m)", GeoPackageDataType.INT),
      FeatureColumn("cargoPierDepth", "Cargo Pier Depth (m)", GeoPackageDataType.INT),
      FeatureColumn("oilTerminalDepth", "Oil Terminal Depth (m)", GeoPackageDataType.INT),
      FeatureColumn("liquifiedNaturalGasTerminalDepth", "Liquefied Natural Gas Terminal Depth (m)", GeoPackageDataType.INT),
      FeatureColumn("maxVesselLength", "Maximum Vessel Length (m)", GeoPackageDataType.INT),
      FeatureColumn("maxVesselBeam", "Maximum Vessel Beam (m)", GeoPackageDataType.INT),
      FeatureColumn("maxVesselDraft", "Maximum Vessel Draft (m)", GeoPackageDataType.INT),
      FeatureColumn("offshoreMaxVesselLength", "Offshore Maximum Vessel Length (m)", GeoPackageDataType.INT),
      FeatureColumn("offshoreMaxVesselBeam", "Offshore Maximum Vessel Beam (m)", GeoPackageDataType.INT),
      FeatureColumn("offshoreMaxVesselDraft", "Offshore Maximum Vessel Draft (m)", GeoPackageDataType.INT),
      FeatureColumn("harborSize", "Harbor Size", GeoPackageDataType.TEXT),
      FeatureColumn("harborType", "Harbor Type", GeoPackageDataType.TEXT),
      FeatureColumn("harborUse", "Harbor Use", GeoPackageDataType.TEXT),
      FeatureColumn("shelter", "Shelter", GeoPackageDataType.TEXT),
      FeatureColumn("entranceRestrictionTide", "Entrance Restriction - Tide", GeoPackageDataType.TEXT),
      FeatureColumn("entranceRestrictionSwell", "Entrance Restriction - Heavy Swell", GeoPackageDataType.TEXT),
      FeatureColumn("entranceRestrictionIce", "Entrance Restriction - Ice", GeoPackageDataType.TEXT),
      FeatureColumn("entranceRestrictionOther", "Entrance Restriction - Other", GeoPackageDataType.TEXT),
      FeatureColumn("overheadLimits", "Overhead Limits", GeoPackageDataType.TEXT),
      FeatureColumn("ukcManagementSystem", "Underkeel Clearance Management System", GeoPackageDataType.TEXT),
      FeatureColumn("goodHoldingGround", "Good Holding Ground", GeoPackageDataType.TEXT),
      FeatureColumn("turningArea", "Turning Area", GeoPackageDataType.TEXT),
      FeatureColumn("portSecurity", "Port Security", GeoPackageDataType.TEXT),
      FeatureColumn("etaMessage", "Estimated Time Of Arrival Message", GeoPackageDataType.TEXT),
      FeatureColumn("quarantinePratique", "Quarantine - Pratique", GeoPackageDataType.TEXT),
      FeatureColumn("quarantineSanitation", "Quarantine - Sanitation", GeoPackageDataType.TEXT),
      FeatureColumn("quarantineOther", "Quarantine - Other", GeoPackageDataType.TEXT),
      FeatureColumn("trafficSeparationScheme", "Traffic Separation Scheme", GeoPackageDataType.TEXT),
      FeatureColumn("vesselTrafficService", "Vessel Traffic Service", GeoPackageDataType.TEXT),
      FeatureColumn("firstPortOfEntry", "First Port Of Entry", GeoPackageDataType.TEXT),
      FeatureColumn("pilotageCompulsory", "Pilotage - Compulsory", GeoPackageDataType.TEXT),
      FeatureColumn("pilotageAvailable", "Pilotage - Available", GeoPackageDataType.TEXT),
      FeatureColumn("pilotageLocalAssist", "Pilotage - Local Assistance", GeoPackageDataType.TEXT),
      FeatureColumn("pilotageAdvisable", "Pilotage - Advisable", GeoPackageDataType.TEXT),
      FeatureColumn("tugsSalvage", "Tugs - Salvage", GeoPackageDataType.TEXT),
      FeatureColumn("tugsAssist", "Tugs - Assistance", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsTelephone", "Communications - Telephone", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsTelegraph", "Communications - Telefax", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsRadio", "Communications - Radio", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsRadioTelephone", "Communications - Radiotelephone", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsAir", "Communications - Airport", GeoPackageDataType.TEXT),
      FeatureColumn("communicationsRail", "Communications - Rail", GeoPackageDataType.TEXT),
      FeatureColumn("searchAndRescue", "Search and Rescue", GeoPackageDataType.TEXT),
      FeatureColumn("navigationArea", "Navigation Area", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesWharves", "Facilities - Wharve", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesAnchor", "Facilities - Anchorage", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesDangerousCargo", "Facilities - Dangerous Cargo Anchorage", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesMedMoor", "Facilities - Med Mooring", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesBeachMoor", "Facilities - Beach Mooring", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesIceMoor", "Facilities - Ice Mooring", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesRoro", "Facilities - RoRo", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesSolidBulk", "Facilities - Solid Bulk", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesLiquidBulk", "Facilities - Liquid Bulk", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesContainer", "Facilities - Container", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesBreakBulk", "Facilities - Breakbulk", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesOilTerminal", "Facilities - Oil Terminal", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesLongTerminal", "Facilities - LNG Terminal", GeoPackageDataType.TEXT),
      FeatureColumn("facilitiesOther", "Facilities - Other", GeoPackageDataType.TEXT),
      FeatureColumn("medicalFacilities", "Medical Facilities", GeoPackageDataType.TEXT),
      FeatureColumn("garbageDisposal", "Garbage Disposal", GeoPackageDataType.TEXT),
      FeatureColumn("chemicalHoldingTankDisposal", "Chemical Holding Tank Disposal", GeoPackageDataType.TEXT),
      FeatureColumn("degauss", "Degaussing", GeoPackageDataType.TEXT),
      FeatureColumn("dirtyBallast", "Dirty Ballast Disposal", GeoPackageDataType.TEXT),
      FeatureColumn("cranesFixed", "Cranes - Fixed", GeoPackageDataType.TEXT),
      FeatureColumn("cranesMobile", "Cranes - Mobile", GeoPackageDataType.TEXT),
      FeatureColumn("cranesFloating", "Cranes - Floating", GeoPackageDataType.TEXT),
      FeatureColumn("cranesContainer", "Cranes - Container", GeoPackageDataType.TEXT),
      FeatureColumn("lifts100", "Lifts - 100+ Tons", GeoPackageDataType.TEXT),
      FeatureColumn("lifts50", "Lifts - 50-100 Tons", GeoPackageDataType.TEXT),
      FeatureColumn("lifts25", "Lifts - 25-49 Tons", GeoPackageDataType.TEXT),
      FeatureColumn("lifts0", "Lifts - 0-24 Tons", GeoPackageDataType.TEXT),
      FeatureColumn("servicesLongshore", "Services - Longshoremen", GeoPackageDataType.TEXT),
      FeatureColumn("servicesElectrical", "Services - Electricity", GeoPackageDataType.TEXT),
      FeatureColumn("servicesSteam", "Services - Steam", GeoPackageDataType.TEXT),
      FeatureColumn("servicesNavigationalEquipment", "Services - Navigational Equipment", GeoPackageDataType.TEXT),
      FeatureColumn("servicesElectricalRepair", "Services - Electrical Repair", GeoPackageDataType.TEXT),
      FeatureColumn("servicesIceBreaking", "Services - Ice Breaking", GeoPackageDataType.TEXT),
      FeatureColumn("servicesDiving", "Services - Diving", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesProvisions", "Supplies - Provisions", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesWater", "Supplies - Potable Water", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesFuel", "Supplies - Fuel Oil", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesDiesel", "Supplies - Diesel Oil", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesAviationFuel", "Supplies - Aviation Fuel", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesDeck", "Supplies - Deck", GeoPackageDataType.TEXT),
      FeatureColumn("suppliesEngine", "Supplies - Engine", GeoPackageDataType.TEXT),
      FeatureColumn("repairCode", "Repair Code", GeoPackageDataType.TEXT),
      FeatureColumn("dryDock", "Dry Dock", GeoPackageDataType.TEXT),
      FeatureColumn("railway", "Railway", GeoPackageDataType.TEXT),
   )
}

class PortFeature(
   port: Port
) : Feature {
   override val geometry = Point(port.longitude, port.latitude)

   override val values = listOf(
      FeatureData("number", port.portNumber),
      FeatureData("name", port.portName),
      FeatureData("latitude", port.latitude),
      FeatureData("longitude", port.longitude),
      FeatureData("position", MGRS.from(port.longitude, port.latitude).coordinate()),
      FeatureData("regionName", "${port.regionName.orEmpty()} - ${port.regionNumber?.toString().orEmpty()}"),
      FeatureData("alternateName", port.alternateName),
      FeatureData("unloCode", port.unloCode),
      FeatureData("countryName", port.countryName),
      FeatureData("dodWaterBody", port.dodWaterBody),
      FeatureData("publicationNumber", port.publicationNumber),
      FeatureData("chartNumber", port.chartNumber),
      FeatureData("s57Enc", port.s57Enc),
      FeatureData("s101Enc", port.s101Enc),
      FeatureData("dnc", port.dnc),
      FeatureData("tide", port.tide?.asNonZeroOrNull()),
      FeatureData("entranceWidth", port.entranceWidth?.asNonZeroOrNull()),
      FeatureData("channelDepth", port.channelDepth?.asNonZeroOrNull()),
      FeatureData("anchorageDepth", port.anchorageDepth?.asNonZeroOrNull()),
      FeatureData("cargoPierDepth", port.cargoPierDepth?.asNonZeroOrNull()),
      FeatureData("oilTerminalDepth", port.oilTerminalDepth?.asNonZeroOrNull()),
      FeatureData("liquifiedNaturalGasTerminalDepth", port.liquifiedNaturalGasTerminalDepth?.asNonZeroOrNull()),
      FeatureData("maxVesselLength", port.maxVesselLength?.asNonZeroOrNull()),
      FeatureData("maxVesselBeam", port.maxVesselBeam?.asNonZeroOrNull()),
      FeatureData("maxVesselDraft", port.maxVesselDraft?.asNonZeroOrNull()),
      FeatureData("offshoreMaxVesselLength", port.offshoreMaxVesselLength?.asNonZeroOrNull()),
      FeatureData("offshoreMaxVesselBeam", port.offshoreMaxVesselBeam?.asNonZeroOrNull()),
      FeatureData("offshoreMaxVesselDraft", port.offshoreMaxVesselDraft?.asNonZeroOrNull()),
      FeatureData("harborSize", port.harborSize?.title),
      FeatureData("harborType", port.harborType?.title),
      FeatureData("harborUse", port.harborUse?.title),
      FeatureData("shelter", port.shelter?.title),
      FeatureData("entranceRestrictionTide", port.entranceRestrictionTide?.title),
      FeatureData("entranceRestrictionSwell", port.entranceRestrictionSwell?.title),
      FeatureData("entranceRestrictionIce", port.entranceRestrictionIce?.title),
      FeatureData("entranceRestrictionOther", port.entranceRestrictionOther?.title),
      FeatureData("overheadLimits", port.overheadLimits?.title),
      FeatureData("overheadLimits", port.overheadLimits?.title),
      FeatureData("ukcManagementSystem", port.ukcManagementSystem?.title),
      FeatureData("goodHoldingGround", port.goodHoldingGround?.title),
      FeatureData("turningArea", port.turningArea?.title),
      FeatureData("portSecurity", port.portSecurity?.title),
      FeatureData("etaMessage", port.etaMessage?.title),
      FeatureData("quarantinePratique", port.quarantinePratique?.title),
      FeatureData("quarantineSanitation", port.quarantineSanitation?.title),
      FeatureData("quarantineOther", port.quarantineOther?.title),
      FeatureData("trafficSeparationScheme", port.trafficSeparationScheme?.title),
      FeatureData("vesselTrafficService", port.vesselTrafficService?.title),
      FeatureData("firstPortOfEntry", port.firstPortOfEntry?.title),
      FeatureData("pilotageCompulsory", port.pilotageCompulsory?.title),
      FeatureData("pilotageAvailable", port.pilotageAvailable?.title),
      FeatureData("pilotageLocalAssist", port.pilotageLocalAssist?.title),
      FeatureData("pilotageAdvisable", port.pilotageAdvisable?.title),
      FeatureData("tugsSalvage", port.tugsSalvage?.title),
      FeatureData("tugsAssist", port.tugsAssist?.title),
      FeatureData("communicationsTelephone", port.communicationsTelephone?.title),
      FeatureData("communicationsTelegraph", port.communicationsTelegraph?.title),
      FeatureData("communicationsRadio", port.communicationsRadio?.title),
      FeatureData("communicationsRadioTelephone", port.communicationsRadioTelephone?.title),
      FeatureData("communicationsAir", port.communicationsAir?.title),
      FeatureData("communicationsRail", port.communicationsRail?.title),
      FeatureData("searchAndRescue", port.searchAndRescue?.title),
      FeatureData("navigationArea", port.navigationArea),
      FeatureData("facilitiesWharves", port.facilitiesWharves?.title),
      FeatureData("facilitiesAnchor", port.facilitiesAnchor?.title),
      FeatureData("facilitiesDangerousCargo", port.facilitiesDangerousCargo?.title),
      FeatureData("facilitiesMedMoor", port.facilitiesMedMoor?.title),
      FeatureData("facilitiesBeachMoor", port.facilitiesBeachMoor?.title),
      FeatureData("facilitiesIceMoor", port.facilitiesIceMoor?.title),
      FeatureData("facilitiesRoro", port.facilitiesRoro?.title),
      FeatureData("facilitiesSolidBulk", port.facilitiesSolidBulk?.title),
      FeatureData("facilitiesLiquidBulk", port.facilitiesLiquidBulk?.title),
      FeatureData("facilitiesContainer", port.facilitiesContainer?.title),
      FeatureData("facilitiesBreakBulk", port.facilitiesBreakBulk?.title),
      FeatureData("facilitiesOilTerminal", port.facilitiesOilTerminal?.title),
      FeatureData("facilitiesLongTerminal", port.facilitiesLongTerminal?.title),
      FeatureData("facilitiesOther", port.facilitiesOther?.title),
      FeatureData("medicalFacilities", port.medicalFacilities?.title),
      FeatureData("garbageDisposal", port.garbageDisposal?.title),
      FeatureData("chemicalHoldingTankDisposal", port.chemicalHoldingTankDisposal?.title),
      FeatureData("degauss", port.degauss?.title),
      FeatureData("dirtyBallast", port.dirtyBallast?.title),
      FeatureData("cranesFixed", port.cranesFixed?.title),
      FeatureData("cranesMobile", port.cranesMobile?.title),
      FeatureData("cranesFloating", port.cranesFloating?.title),
      FeatureData("cranesContainer", port.cranesContainer?.title),
      FeatureData("lifts100", port.lifts100?.title),
      FeatureData("lifts50", port.lifts50?.title),
      FeatureData("lifts25", port.lifts25?.title),
      FeatureData("lifts0", port.lifts0?.title),
      FeatureData("servicesLongshore", port.servicesLongshore?.title),
      FeatureData("servicesElectrical", port.servicesElectrical?.title),
      FeatureData("servicesSteam", port.servicesSteam?.title),
      FeatureData("servicesNavigationalEquipment", port.servicesNavigationalEquipment?.title),
      FeatureData("servicesElectricalRepair", port.servicesElectricalRepair?.title),
      FeatureData("servicesIceBreaking", port.servicesIceBreaking?.title),
      FeatureData("servicesDiving", port.servicesDiving?.title),
      FeatureData("suppliesProvisions", port.suppliesProvisions?.title),
      FeatureData("suppliesWater", port.suppliesWater?.title),
      FeatureData("suppliesFuel", port.suppliesFuel?.title),
      FeatureData("suppliesDiesel", port.suppliesDiesel?.title),
      FeatureData("suppliesAviationFuel", port.suppliesAviationFuel?.title),
      FeatureData("suppliesDeck", port.suppliesDeck?.title),
      FeatureData("suppliesEngine", port.suppliesEngine?.title),
      FeatureData("repairCode", port.repairCode?.title),
      FeatureData("dryDock", port.dryDock?.title),
      FeatureData("railway", port.railway?.title)
   )
}