name: Build

on:
  workflow_dispatch:
    inputs:
      appBranch:
        description: 'App GitHub branch to build'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Specified Branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.appBranch }}
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" > release.b64
        base64 -d release.b64 > release.keystore
    - name: Build with Gradle
      run: |
        ./gradlew clean assembleRelease \
        -PKEYSTORE=../release.keystore \
        -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
        -PKEY_ALIAS=${{ secrets.ALIAS }} \
        -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
        -PMSI_RELEASE_MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
    - name: Verify Signature
      run: $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --print-certs app/build/outputs/apk/release/app-release.apk
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
